preprocess:
    lidar_type: 4                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 4 RSHelios32
    transform_frame_id: true     # 是否转发消息，区分各个雷达的frame_id
    CompressedImage: true        #图像格式是sensor_msgs/CompressedImage 还是sensor_msgs/Image
    lidar_back_left_helios32: true      #是否融合此雷达
    # lidar_back_up_helios32: false        #是否融合此雷达
    lidar_front_right_helios32: true    #是否融合此雷达
    # lidar_front_up_helios32: false       #是否融合此雷达
    # rslidar_points_airy_front: false     #是否融合此雷达
    # rslidar_points_airy_rear: false      #是否融合此雷达
    # rslidar_points_m1p_front: false      #是否融合此雷达
    # rslidar_points_m1p_rear: false       #是否融合此雷达